"use client";

import {
  ChevronRight,
  FileText,
  HelpCircle,
  MoreVertical,
  Plus,
  Search,
  Settings,
  UserRound,
  WalletCards,
} from "lucide-react";
import { Cell, Pie, PieChart } from "recharts";

import {
  PAYROLL_RUN_KPI_DATA,
  PAYROLL_RUN_STATUS_DATA,
  PAYROLL_RUN_TABLE_DATA,
  PAYROLL_RUN_YEAR_SUMMARY,
} from "@/constants/admin-dashboard";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/ui/chart";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { cn } from "@/lib/utils";
import { IconCreditCardFilled } from "@tabler/icons-react";

export function PayrollRunsOverview() {
  return (
    <div className="flex flex-col gap-5">
      <PageHeader
        title="Payroll Runs"
        description="Review payroll history, statuses, and generated payroll batches."
        actionLabel="New Payroll Run"
      />
      <PayrollRunKpis />
      <PayrollRunsTableCard />
    </div>
  );
}

function PayrollRunKpis() {
  return (
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
      {PAYROLL_RUN_KPI_DATA.map((item) => (
        <MetricCard
          key={item.title}
          title={item.title}
          value={item.value}
          note={item.note}
        />
      ))}
    </section>
  );
}

function PayrollRunsTableCard() {
  return (
    <Card className="overflow-hidden rounded-xl border-zinc-200 px-5 py-4 shadow-xs">
      <div className="flex flex-wrap items-center gap-3">
        <div className="relative min-w-64">
          <Search className="absolute right-3 top-1/2 size-3.5 -translate-y-1/2 text-slate-400" />
          <Input
            className="h-9 text-xs! bg-transparent border-input pr-9"
            placeholder="Search payroll runs..."
          />
        </div>
        <FilterSelect
          value="all-statuses"
          options={[
            "All Statuses",
            "Completed",
            "Processing",
            "Draft",
            "Cancelled",
          ]}
        />
        <FilterSelect
          value="all-pay-types"
          options={["All Pay Types", "Regular Payroll", "Bonus"]}
        />
      </div>
      <Table>
        <TableHeader className="bg-zinc-50">
          <TableRow>
            <TableHead>Payroll Name</TableHead>
            <TableHead>Pay Period</TableHead>
            <TableHead>Pay Date</TableHead>
            <TableHead>Pay Type</TableHead>
            <TableHead>Employees</TableHead>
            <TableHead>Total Net Pay</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>Generated By</TableHead>
            <TableHead>Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {PAYROLL_RUN_TABLE_DATA.map((item) => (
            <TableRow key={item.runId} className="h-16">
              <TableCell>
                <p className="font-semibold">{item.name}</p>
                <p className="text-xs text-slate-500">{item.runId}</p>
              </TableCell>
              <TableCell>{item.period}</TableCell>
              <TableCell>{item.payDate}</TableCell>
              <TableCell>
                <PayTypeBadge type={item.type} />
              </TableCell>
              <TableCell>{item.employees}</TableCell>
              <TableCell className="font-semibold">{item.netPay}</TableCell>
              <TableCell>
                <StatusBadge status={item.status} note={item.statusNote} />
              </TableCell>
              <TableCell>
                <div className="flex items-center gap-3">
                  <Avatar>
                    <AvatarFallback>AD</AvatarFallback>
                  </Avatar>
                  <div>
                    <p className="font-semibold">{item.generatedBy}</p>
                    <p className="text-xs text-slate-500">
                      {item.generatedRole}
                    </p>
                  </div>
                </div>
              </TableCell>
              <TableCell>
                <Button variant="ghost" size="icon" className="size-8">
                  <MoreVertical className="size-4" />
                </Button>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
      <div className="flex items-center justify-between border-t border-zinc-200 px-4 py-3 text-xs text-zinc-600">
        <span>Showing 1 to 10 of 18 payroll runs</span>
        <div className="flex items-center gap-1.5">
          <span>Rows per page</span>
          <Select defaultValue="10">
            <SelectTrigger size="sm" className="h-8 w-20 text-xs">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="10">10</SelectItem>
            </SelectContent>
          </Select>
          <Button size="icon-sm" className="text-xs">
            1
          </Button>
          <Button variant="outline" size="icon-sm" className="text-xs">
            2
          </Button>
        </div>
      </div>
    </Card>
  );
}

function PageHeader({
  title,
  description,
  actionLabel,
}: {
  title: string;
  description: string;
  actionLabel: string;
}) {
  return (
    <div className="flex flex-wrap items-start justify-between gap-3">
      <div className="flex items-center gap-2">
        <IconCreditCardFilled className="size-4 text-zinc-900" />
        <ChevronRight className="size-4 text-zinc-500" />
        <div>
          <h1 className="text-lg font-bold tracking-tight text-zinc-950">
            {title}
          </h1>
          <p className="sr-only">{description}</p>
        </div>
      </div>
      <div className="flex gap-2">
        <Button
          variant="secondary"
          className="rounded-lg bg-zinc-200 px-3 text-xs font-semibold text-zinc-800 hover:bg-zinc-300"
        >
          Export
        </Button>
        <Button className="rounded-lg bg-zinc-900 px-4 text-xs font-semibold text-white shadow-sm hover:bg-zinc-800">
          {actionLabel}
        </Button>
      </div>
    </div>
  );
}

function MetricCard({
  title,
  value,
  note,
}: {
  title: string;
  value: string;
  note: string;
}) {
  return (
    <Card
      key={title}
      className="min-h-17 rounded-xl border-zinc-200 bg-white px-4 py-4 shadow-xs"
    >
      <div className="flex h-full items-end justify-between gap-4">
        <div className="min-w-0">
          <p className="w-fit border-b border-dotted border-zinc-400 text-xs font-bold text-zinc-700">
            {title}
          </p>
          <p className="mt-1 text-base font-bold tracking-tight text-zinc-900">
            {value}
          </p>
          <p className="mt-1 text-xs font-normal text-zinc-500">{note}</p>
        </div>
      </div>
    </Card>
  );
}

function FilterSelect({
  value,
  options,
}: {
  value: string;
  options: string[];
}) {
  return (
    <Select defaultValue={value}>
      <SelectTrigger size="sm" className="h-9 w-44 text-xs">
        <SelectValue />
      </SelectTrigger>
      <SelectContent>
        {options.map((option, index) => (
          <SelectItem key={option} value={index === 0 ? value : option}>
            {option}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

function YearSummaryCard() {
  return (
    <Card className="rounded-lg border-slate-200 p-5 shadow-sm">
      <h3 className="font-bold">Payroll Summary (This Year)</h3>
      <div className="mt-5 space-y-4 text-sm">
        {PAYROLL_RUN_YEAR_SUMMARY.map(([label, value]) => (
          <div key={label} className="flex justify-between gap-3">
            <span className="text-slate-600">{label}</span>
            <span className="font-bold">{value}</span>
          </div>
        ))}
      </div>
    </Card>
  );
}

function StatusBreakdownCard() {
  return (
    <Card className="rounded-lg border-slate-200 p-5 shadow-sm">
      <h3 className="font-bold">Status Breakdown</h3>
      <div className="relative mt-4">
        <ChartContainer
          config={{ value: { label: "Runs" } }}
          className="mx-auto h-44 aspect-square"
        >
          <PieChart>
            <ChartTooltip content={<ChartTooltipContent hideLabel />} />
            <Pie
              data={PAYROLL_RUN_STATUS_DATA}
              dataKey="value"
              nameKey="name"
              innerRadius={44}
              outerRadius={64}
            >
              {PAYROLL_RUN_STATUS_DATA.map((entry) => (
                <Cell key={entry.name} fill={entry.fill} />
              ))}
            </Pie>
          </PieChart>
        </ChartContainer>
      </div>
      <div className="space-y-2 text-sm">
        {PAYROLL_RUN_STATUS_DATA.map((item) => (
          <div key={item.name} className="flex justify-between gap-3">
            <span className="flex items-center gap-2">
              <span
                className="size-2 rounded-full"
                style={{ backgroundColor: item.fill }}
              />
              {item.name} ({item.value})
            </span>
            <span className="font-semibold">{item.note}</span>
          </div>
        ))}
      </div>
    </Card>
  );
}

function QuickActionsCard() {
  const actions = [
    ["Generate Payroll", "Create a new payroll run", WalletCards],
    ["Payroll Summary", "View payroll summary report", FileText],
    ["Payslips", "View all employee payslips", UserRound],
    ["Payroll Settings", "Configure payroll preferences", Settings],
  ] as const;

  return (
    <Card className="rounded-lg border-slate-200 p-5 shadow-sm">
      <h3 className="font-bold">Quick Actions</h3>
      <div className="mt-4 space-y-4 text-sm">
        {actions.map(([title, note, Icon]) => (
          <div key={title} className="flex gap-3">
            <span className="flex size-8 items-center justify-center rounded-md bg-blue-50 text-blue-600">
              <Icon className="size-4" />
            </span>
            <div>
              <p className="font-semibold">{title}</p>
              <p className="text-xs text-slate-500">{note}</p>
            </div>
          </div>
        ))}
      </div>
    </Card>
  );
}

function HelpCard() {
  return (
    <Card className="rounded-lg border-blue-100 bg-blue-50 p-5 shadow-sm">
      <div className="flex gap-3">
        <HelpCircle className="size-5 text-blue-600" />
        <div>
          <h3 className="font-bold text-blue-900">Need Help?</h3>
          <p className="mt-2 text-sm text-blue-700">
            Learn more about payroll processing
          </p>
          <Button variant="outline" className="mt-4 bg-white text-blue-600">
            View Help Center
          </Button>
        </div>
      </div>
    </Card>
  );
}

function StatusBadge({ status, note }: { status: string; note: string }) {
  return (
    <div>
      <Badge
        variant="secondary"
        className={cn("rounded-md", statusClass(status))}
      >
        {status}
      </Badge>
      {note ? <p className="mt-1 text-xs text-slate-500">{note}</p> : null}
    </div>
  );
}

function PayTypeBadge({ type }: { type: string }) {
  return (
    <Badge
      variant="secondary"
      className={cn(
        type === "Bonus"
          ? "bg-orange-50 text-orange-700"
          : "bg-blue-50 text-blue-700",
      )}
    >
      {type}
    </Badge>
  );
}

function statusClass(status: string) {
  if (status === "Completed") return "bg-emerald-50 text-emerald-700";
  if (status === "Processing") return "bg-amber-50 text-amber-700";
  if (status === "Draft") return "bg-violet-50 text-violet-700";
  return "bg-red-50 text-red-700";
}
